# Generated by Django 2.2.5 on 2019-09-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190930_1154'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='db_project',
        ),
    ]
