# Generated by Django 2.2.5 on 2019-09-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190930_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '人类', 'verbose_name_plural': '人类'},
        ),
    ]
