# Generated by Django 2.2.5 on 2019-09-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190930_1652'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='db_projects',
        ),
    ]
